apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: http://10.241.2.12:3128 
  httpsProxy: http://10.241.2.12:3128 
  noProxy: s3.direct.us.cloud-object-storage.appdomain.cloud
  readinessEndpoints:
  - http://www.google.com 
  - https://www.google.com
  trustedCA:
    name: ""